### ISSUE TITLE
Support for other types for Github Checks?

### ISSUE THREAD

**Issue by ndench** [phstc/probot-merge-when-green#29]
Is it possible for this to support any check against a PR? Specifically we use AWS CodeBuild, but I would have thought GitHub would abstract so to make it easy to work with any type of check?

**Comment by phstc** [comment]
Hi @ndench 

Making Merge when green more flexible would be great. In the current implementation, CircleCI and Travis are hardcoded [here](https://github.com/phstc/probot-merge-when-green/blob/bc92faa7b57c2c0457178a0965b3dd6fc7f8967a/src/constants.ts#L2).

The bot could use [probot-config](https://github.com/probot/probot-config) to allow defining custom services, keeping the defaults to CircleCI and Travis.

As long as it gets the list of service names, it should ✨ work [here](https://github.com/phstc/probot-merge-when-green/blob/bc92faa7b57c2c0457178a0965b3dd6fc7f8967a/src/mergeIfGreen.ts#L20).

WDYT?

**Comment by ndench** [comment]
Hey @phstc, thanks for the quick response!

That sounds like it would work. But I'm not sure why `SUPPORTED_CI` is required? What if you don't filter `checks.checkRuns`? Would this not ensure that every check passes?

**Comment by phstc** [comment]
@ndench we could make it optional using probot-config. There are some cases we don't want to enforce all checks, for example, those for code styling. 

Another optionI is to check the branch protection 👇 

![image](https://user-images.githubusercontent.com/105652/61250383-88aa4700-a725-11e9-8ccc-3af78762b90d.png)

MWG would respect whatever is configured in there. And people without it configured, it would check for all checks. WDYT?

Do you have branch protection enabled?

**Comment by ndench** [comment]
@phstc Yeah that makes sense. Personally have branch protection enabled on all my repos, and make every check required. I don't really see the point of having an automatic check that you ignore, you'll either have to fix it later or it's not really providing you any value.

That being said, I'm sure some other people have use cases and reasons for not wanting automatic merging when some subset of their checks pass. I think the most flexible approach would be to follow whatever branch protection is configured by default, and people can configure additional checks with probot-config.

Do you need any help with this? Happy to beta test or help out if you need.

**Comment by phstc** [comment]
@ndench that sounds good. Would you be interesting on creating a PR?

https://octokit.github.io/rest.js/#octokit-routes-repos-get-branch-protection

I would create a function `getSupportedChecks` that would call the API ☝️, if the API does not have any checker selected, then it would look for the probot-config.

**Comment by phstc** [comment]
For breaking it down in steps, the first pull request could be just using probot-config, if not configured, fallback to the current checks.

**Comment by ndench** [comment]
@phstc ok I'll take a shot at it :+1:
