### ISSUE TITLE
Support for commit statuses?

### ISSUE THREAD

**Issue by ndench** [phstc/probot-merge-when-green#31]
Getting support for other types of Checks in #29 is really great but Checks are really quite new. Most CI tools still use [Statuses](https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref) which are slightly less valuable, but would still work great with Merge when green.

I think adding support for Statuses would be quite simple, and would make this app applicable for so many more projects. I propose we use the [list statuses for specific ref api](https://octokit.github.io/rest.js/#octokit-routes-repos-list-statuses-for-ref) in the same way as we get checks:

```javascript
  // Getting the checks as we do already
  const checks = (await context.github.checks.listForRef(
    context.repo({ ref: pr.head.ref })
  )).data
 
  // Get statuses as well
  const statuses = (await context.github.repos.listStatusesForRef(
    context.repo({ ref: pr.head.ref })
  )).data
```

More that happy to send through a PR if you're happy for this functionality to be included @phstc?

**Comment by phstc** [comment]
@ndench that looks great. I will be more than happy with statuses support. Thanks again!

One challenging part would be [this](https://github.com/phstc/probot-merge-when-green/blob/d9d21753ac9a3c0f83b5d67e921756811ee2b0df/src/index.ts#L8-L10). Now MWG receives a webhook call every time a check is completed. I believe [`status.success`](https://developer.github.com/v3/activity/events/types/#statusevent) would work similarly, but the challenge is that with `check.completed` we get list of associated pull requests to the ref, and we don't with status. 

I may be overcomplicating this, but it seems we would have to find all pull requests, labeled with `merge when green` that the HEAD is equal to the receive status SHA. Does that make sense?

**Comment by ndench** [comment]
@phstc sorry for the late reply.

It seems you're right, this might be more difficult than I anticipated. I've found a few ways we can get the pull requests associated with the status

Unfortunately we can't [list pull requests filtered by label](https://developer.github.com/v3/pulls/#list-pull-requests), we can [list issues filtered by label](https://developer.github.com/v3/issues/#list-issues) and that will include pull requests, which can be identified by finding the `pull_request` which we'd then have to do another request to get the pull request data for each one, then we'd have to iterate through and find the ones with the correct HEAD value.

Option 2 would be to just list all pull requests and iterate through filtering out the ones without the correct HEAD value or the MWG label.

Option 3 is using the commit api to [list pull requests associated with a commit](https://developer.github.com/v3/repos/commits/#list-pull-requests-associated-with-commit), see the [sdk docs here](https://octokit.github.io/rest.js/#octokit-routes-repos-list-pull-requests-associated-with-commit). Note, this is currently in preview so it might change. We would then iterate through them and filter the ones with MWG label.

Personally, I prefer option 3 even though the api is in preview it seems cleaner and will avoid the problem of when the status is for a previous commit in the pull request (ie. not the HEAD).

Which option do you prefer?

**Comment by phstc** [comment]
Hi @ndench - you rock!

That's nice research. I agree with you, I believe option 3) is the best.

For the option 3, how would we compare if the status is Circle CI or Travis? For Checks we use [`app.owner.login`](https://github.com/phstc/probot-merge-when-green/blob/master/src/mergeIfGreen.ts#L23).

1. Add webhook for status.succeed
2. Find out if the status is from a service we need to check (Circle CI, Travis etc) or not. 
3. Find matching pull requests 
4. Filter out pull requests not labeled with MWG
5. Merge When Green

**Comment by ndench** [comment]
To see if the status is one we care about, I think `context` would be the best option, though statuses do also have `creator.login`. See the [statuses docs](https://developer.github.com/v3/repos/statuses/). The reason I like `context` is that's what's shown on every pull request so it's easier for users to get. Instead of tracking down the username of the creator, which could be anything. Also, it's more granular because a single creator could make many different statuses.

As soon as I started to implement this, I ran into a problem. The `listPullRequestsAssociatedWithCommit()` feature was added to octokit in [version 16.24.1](https://github.com/octokit/rest.js/releases/tag/v16.24.1) which means we have to upgrade probot a couple of major versions. We're on 7 and we need 9.

Is there anything that you're aware of that will break during the upgrade? Should we do the upgrade separately to this change or bundle it in the same PR?

**Comment by phstc** [comment]
Hi @ndench 

Thanks for looking into this. I think it is fine to upgrade to a couple major versions. I think we will easily find any possible errors, hopefully TS will also help to confirm breaking changes. 

Two pull requests would be great, so we can isolate changes.
