### ISSUE TITLE
Support for requested reviewers

### ISSUE THREAD

**Issue by ndench** [phstc/probot-merge-when-green#42]
After implementing #36 we'll effectively we waiting on a the number of required reviewers. However GitHub also lets you request reviews from people because PR author might want more than 1 person to review their changes as they have touched different areas of the codebase for instance. 

I propose adding a bool flag to config such as:

```
requireRequestedApprovals: true
```

Which will cause MWG to wait until all requested reviewers have arrived the PR. 

My idea for accomplishing this is by [listing reviews on a pull request](https://octokit.github.io/rest.js/#octokit-routes-pulls-list-reviews) and filtering for any that are PENDING.

**Comment by phstc** [comment]
There's [this workaround](https://github.com/phstc/probot-merge-when-green/blob/master/src/index.ts#L17-L19) for that. MWG fails to merge if all statuses pass, but if one or more approvals are required and since it is also listening for `pull_request_review` every time an approval happens, it tries to merge again until it succeeds.

**Comment by ndench** [comment]
Yeah that's a good point.it works when you set branch protection to require 1 or more approvals before merging.

However my use case is that we require one approval in branch protection but for some pull requests we request reviews from 2 or more people. As soon as a single one approves then branch protection is satisfied even though there are still pending reviews.

The reason I would request reviews from more than one person is that I'm touching different areas of the codebase that were written by different people, so no one person can actually review the entire thing.

But we don't want to set branch protection to require more than one approval because most of the we only need one approval.

Does that make sense?

**Comment by phstc** [comment]
Oh, I see what do you mean. I misread the issue description.

I was wondering if something more verbose would help to make it more explicit.

```
requireApprovalFromRequestedReviewers: true
```

**Comment by ndench** [comment]
Yep, that's a much better name!
