### ISSUE TITLE
Bot doesn't work

### ISSUE THREAD

**Issue by orsinium** [phstc/probot-merge-when-green#6]
Sorry for the useless title, but I don't know how to debug it.

PR example:
https://github.com/dephell/dephell/pull/47

App added to the organization and has access to all repositories. Label added to the issue. CI checks have passed.

**Comment by phstc** [comment]
Hi @orsinium 

How did you install the app? Did you install through https://github.com/apps/merge-when-green?

For using it with Travis, you need to enable GitHub Checks: https://blog.travis-ci.com/2018-05-07-announcing-support-for-github-checks-api-on-travis-ci-com

**Comment by orsinium** [comment]
Wow, <travis-ci.org> doesn't work through the checks mechanism. It works for <travis-ci.com>, but this new CI [doesn't support OSS](https://docs.travis-ci.com/user/migrate/open-source-on-travis-ci-com/#existing-open-source-repositories-on-travis-ciorg) yet.

Now it's clear. Thank you!

**Comment by phstc** [comment]
Hi @orsinium 

hm I didn't know that 😞 

It's working for this repo, but it seems it is using travis-ci.com: https://github.com/phstc/probot-merge-when-green/pull/4/checks

Is Travis still accepting new repo in travis-ci.org or are they migrating everybody to travis-ci.com?

**Comment by orsinium** [comment]
Dot com version available only by request

> Open source projects and their build history will continue to run on travis-ci.org at this time.

> However, you can be included in the closed beta testing to start migrating your open source repositories to travis-ci.com.

It shows all my repos as unavailable for migration.
